### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ilyydy** [D-Y-Innovations/interview_xzl#1]
- [ ] 安装 typescript 这个库, 配置 tsconfig.json， https://www.tslang.cn/docs/handbook/tsconfig-json.html， 增加合适的类型定义

- [ ] require 改成用 import ，如 https://github.com/D-Y-Innovations/interview_xzl/blob/master/interview_answer2.0_xzl/code/Crawler.ts#L4

- [ ] 有些用 let 定义的变量应该改成用 const，不应该用 var
